### ISSUE TITLE
Any way to edit custom version / signature

### ISSUE THREAD

**Issue by orenyk** [cbetta/hackcoc#15]
Hi, I used the Hack Code of Conduct for a [past event](http://hackcodeofconduct.org/hackathonukah2014) and wanted to repurpose my signature / custom version for a different upcoming event (run by the same organization). I was wondering if there was any way to edit the URL / update the contact info for an existing signature, or if I'd have to create a new for each event (and just have duplicate signatures on the document). Any help would be greatly appreciated, thanks!

**EDIT** After quickly browsing through the code I'm guessing that this is not possible since the `SupportersController` doesn't have any `edit` / `update` actions. Let me know how you think I should proceed.

**Comment by cbetta** [comment]
Editing us still a work in progress. Email me unit changes and I'll add
them.

On Thu, 31 Mar 2016 04:51 Oren Kanner, <notifications@github.com> wrote:

> Hi, I used the Hack Code of Conduct for a past event
> <http://hackcodeofconduct.org/hackathonukah2014> and wanted to repurpose
> my signature / custom version for a different upcoming event (run by the
> same organization). I was wondering if there was any way to edit the URL /
> update the contact info for an existing signature, or if I'd have to create
> a new for each event (and just have duplicate signatures on the document).
> Any help would be greatly appreciated, thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cbetta/hackcoc/issues/15>
>
-- 
Cristiano Betta
Developer Advocate @ PayPal
+44(0)7518397784
