### ISSUE TITLE
Reports phone number as invalid

### ISSUE THREAD

**Issue by aidan-fitz** [cbetta/hackcoc#18]
On the page to edit my signature, the page gives me the error message that my phone number, in the format xxxxxxxxxx or xxx-xxx-xxxx, is invalid.

**Comment by cbetta** [comment]
@aidan-fitz try adding it in internation format +1 333 4444 5555 etc

**Comment by aidan-fitz** [comment]
It worked, but I mean.... Can you add a note specifying the format that users have to write it in?

**Comment by cbetta** [comment]
@aidan-fitz will do! I used a gem and tbh I just made a guess about what format it expected :)

**Comment by cbetta** [comment]
Closing, made the warning clearer
