### ISSUE TITLE
Licencing of Text

### ISSUE THREAD

**Issue by danielrbradley** [cbetta/hackcoc#22]
Hi, I'd love to use this for an event I'm helping organise, but I couldn't find any reference to what licence you've released the text under (at which point I'm assuming it's considered copyrighted?)

Would it be possible to specify a licence, perhaps either under [public domain](https://creativecommons.org/publicdomain/) or [Creative Commons Attribution 4.0](https://choosealicense.com/licenses/cc-by-4.0/), along with guidance around if a link back to your site is required?

**Comment by cbetta** [comment]
Hi @danielrbradley, thank you for pointing this out, it should indeed have a license on it. I will review the app's license and the CoC's content's license somewhere today.

**Comment by cbetta** [comment]
@danielrbradley this has now been resolved. The text copy of the HackCoC is now available under CC0, the Rails application powering the moderation is available under MIT.
