### ISSUE TITLE
Removal of data/Trying to update but get 500

### ISSUE THREAD

**Issue by zaccolley** [cbetta/hackcoc#25]
When I go to update and submit my email the page errors:
> The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.

If this can't be solved can I have my details removed manually somehow?

Thanks for your help.

https://hackcodeofconduct.org/hackpompey is the page to be removed and the email that errors

**Comment by cbetta** [comment]
Sure thing, happy to remove it! Can you just email me from the email listed on that page, just to confirm your identity?

**Comment by zaccolley** [comment]
Thanks for the quick response 👍 

Ahh, I don't have access to send from that email anymore. I have it forwarding to my other email though.

A pain but could you email that email (zac [ AT] rosedigital) and then I will respond from zaccolley [AT] gmail?

**Comment by cbetta** [comment]
I emailed zac [ AT] rosedigital [dot] com and got a bounce message.

**Comment by zaccolley** [comment]
Oops, it's .co.uk sorry

**Comment by zaccolley** [comment]
Hey @cbetta sorry to bother you, could you try with .co.uk?

**Comment by cbetta** [comment]
Done

**Comment by zaccolley** [comment]
Looks like the email MX DNS records had been removed so the emails were not being forwarded. Sorry that account hasn't been used in a few days. I've tested it forwards to the right place now.

One more try to zac [@] rosedigital [dot] co [dot] uk should work

**Comment by cbetta** [comment]
All done. Tnx for confirming.

**Comment by zaccolley** [comment]
@cbetta thanks for hanging in there aha!
