### ISSUE TITLE
Can't edit my Submission

### ISSUE THREAD

**Issue by muntasiraonik** [cbetta/hackcoc#26]
Hei, I have submitted my email to get edit access to my submission and it's not working. I didn't get any email. I want to remove my submission. Please tell me about the process. :(

**Comment by cbetta** [comment]
@muntasiraonik let me know which entry is yours and ill remove it

**Comment by muntasiraonik** [comment]
Muntasir Aonik

Website:
https://www.gamingspice.com
https://www.trusteepress.com

**Comment by cbetta** [comment]
All removed!
