### ISSUE TITLE
References to law enforcement

### ISSUE THREAD

**Issue by edent** [cbetta/hackcoc#8]
There is a reference to law enforcement as:

> Hackathon staff will be happy to help participants contact any local security or local law enforcement

Is it worth making it more explicit in the next section? Perhaps by including language like:

>  If a participant engages in harassing behavior, the hackathon organisers may take any action they deem appropriate, including warning the offender, expulsion from the hackathon with no refund (if applicable),  *or reporting their behaviour to local law enforcement*. 

Just to make it clear that illegal behaviour won't be swept under the carpet.

**Comment by cbetta** [comment]
Love it, currently on limited time but if you can create a PR I can merge it.
